<#global SINGLETON_IND = 'SINGLETON_IND'>
  <#global LEVELNAME = {'COMPOSITE_ENTITY': 'Top level'}>
    <#global ENTITY = {'SUBSTANCE': 'SUBSTANCE', 'MIXTURE': 'MIXTURE', 'TEMPLATE': 'TEMPLATE'}>
      <#global SECTION = {'ROOT': 'ROOT', 'ACTIVE': 'ACTIVE', 'NON_ACTIVE': 'NON_ACTIVE', 'DISTANT_DESCENDANTS':  'DISTANT_DESCENDANTS'}>
        <#global TABLE = {
          'ROOT'                : 'ROOT',
          'ACTIVE'              : 'ACTIVE',
          'NON_ACTIVE'          : 'NON_ACTIVE',
          'DISTANT_DESCENDANTS' :  'DISTANT_DESCENDANTS'
        }>
          <#global FIELD = {
            'name': 'name',
            'type': 'type',
            'authority': 'authority',
            'dataProtection': 'dataProtection',
            'docType': 'docType',
            'status': 'status',
            'confidentiality': 'confidentiality',
            'agreement': 'agreement',
            'evalInfo': 'evalInfo',
            'remarks': 'remarks',
            'isWaiverable': 'isWaiverable',
            'entityName': 'entityName',
            'entityType': 'entityType',
            'entityID': 'entityID',
            'entityDoc': 'entityDoc',
            'sectionNode': 'sectionNode',
            'sectionName': 'sectionName',
            'sectionNumber': 'sectionNumber',
            'sectionDocType': 'sectionDocType',
            'entityFunction': 'entityFunction',
            'docID': 'docID',
            'docUrl': 'docUrl',
            'sectionDoc': 'sectionDoc',
            'sectionDocAnnots': 'sectionDocAnnots',
            'key': 'key',
            'reliability': 'reliability',
            'isActiveSubstanceOfRoot': 'isActiveSubstanceOfRoot',
            'level': 'level',                     
            'historyList': 'historyList'
          }>
<#global SECTION_TO_ANNEX_REQUIREMENT =
{'1.3': 'Biocidal product manufacturer',
'1.3.1': 'Location of manufacturing plants',
'10': 'ENVIRONMENTAL FATE AND BEHAVIOUR',
'10.1': 'Foreseeable routes of entry into the environment on the basis of the use envisaged',
'10.1.1.1.a': 'Abiotic: Hydrolysis as a function of pH and identification of breakdown products',
'10.1.1.1.b': 'Abiotic: Phototransformation in water, including identification of transformation products',
'10.1.1.2': 'Biotic --> Ready / inherent biodegradability',
'10.1.2': 'Adsorption / desorption',
'10.1.3': 'Rate and route of degradation including identification of metabolites and degradation products',
'10.1.5': 'Field studies',
'10.2': 'Further studies on fate and behaviour in the environment',
'10.2.1': 'Laboratory study on rate and route of degradation including identification of the processes involved',
'10.2.3': 'Soil accumulation studies',
'10.3': 'Leaching behaviour',
'10.3.1': 'Phototransformation in air (estimation method)',
'10.4': 'Testing for distribution and dissipation',
'10.6': 'Monitoring: Identification of all degradation products (>10%) must be included in the studies on degradation in soil, water and sediments',
'11': 'Measures to protect humans, animals and the environment',
'12.1': 'GHS',
'12.2': 'DSD - DPD',
'12.3': 'Packaging (12.7 in Annex III of BPR) (type, materials, size, etc ), compatibility of the product with proposed packaging materials to be included',
'13': 'SUMMARY AND EVALUATION',
'18.12.2': 'Direct observations: clinical cases, poisoning incidents and other',
'18.12.4': 'Epidemiological data',
'2.1': 'Trade name or proposed trade name',
'2.2': "Manufacturer's development code and number of the biocidal product, if appropriate",
'2.3': 'Biocidal product composition',
'3': 'PHYSICAL, CHEMICAL AND TECHNICAL PROPERTIES',
'3.1': 'Appearance (at 20°C and 101.3 kPa)',
'3.11': 'Thermal stability, identity of breakdown products',
'3.12': 'Reactivity towards container material',
'3.13': 'Dissociation constant',
'3.14': 'Granulometry',
'3.15': 'Viscosity',
'3.16': 'Solubility in organic solvents, including effect of temperature on solubility',
'3.17': 'Stability in organic solvents used in biocidal products and identity of relevant breakdown products',
'3.18.1': 'Nanomaterial agglomeration / aggregation',
'3.18.10': 'Nanomaterial pour density',
'3.18.11': 'Nanomaterial photocatalytic activity',
'3.18.12': 'Nanomaterial radical formation potential',
'3.18.13': 'Nanomaterial catalytic activity',
'3.18.2': 'Nanomaterial crystalline phase',
'3.18.3': 'Nanomaterial crystallite and grain size',
'3.18.4': 'Nanomaterial aspect ratio / shape',
'3.18.5': 'Nanomaterial specific surface area',
'3.18.6': 'Nanomaterial Zeta potential',
'3.18.7': 'Nanomaterial surface chemistry',
'3.18.8': 'Nanomaterial dustiness',
'3.18.9': 'Nanomaterial porosity',
'3.2': 'Acidity, alkalinity',
'3.3': 'Relative density (liquids) and bulk, tap density (solids)',
'3.4': 'Boiling point',
'3.4.1': 'Storage stability tests',
'3.4.2.1': 'Light',
'3.5': 'Technical characteristics of the biocidal product',
'3.6': 'Physical and chemical compatibility with other products',
'3.7': 'Degree of dissolution and dilution stability',
'3.7.1': 'Vapour pressure',
'3.7.2': "Henry's law constant",
'3.8': 'Surface tension',
'3.9': 'Viscosity',
'4.1': 'Explosives',
'4.15': 'Organic peroxides                          ',
'4.16': 'Corrosive to metals                         ',
'4.17': 'Additional physical indicators for hazards                       ',
'4.17.1': 'Auto-ignition temperature (liquids and gases)                       ',
'4.2': 'Flammability',
'4.4': 'Oxidising properties',
'4.5': 'Gases under pressure                         ',
'4.6': 'Flammable liquids                          ',
'4.8': 'Self-reactive substances and mixtures                        ',
'5': 'METHODS OF DETECTION AND IDENTIFICATION',
'6': 'EFFECTIVENESS AGAINST TARGET ORGANISMS ',
'6.1': 'Function, e.g. fungicide, rodenticide, insecticide, bactericide  and mode of control e.g. attracting, killing, inhibiting',
'6.6': 'Efficacy data to support these claims on biocidal products and, where label claims are made, on treated articles, including any available standard protocols, laboratory tests or field trials used including performance standards where appropriate',
'6.7': 'Efficacy data to support these claims, including any available standard protocols, laboratory tests or field trials used including performance standards where appropriate and relevant',
'7.1': 'Field(s) of use envisaged for biocidal products and, where appropriate, treated articles',
'7.5': 'Likely tonnage to be placed on the market per year and, where relevant, for different use categories',
'7.6': 'Method of application and a description of this method',
'8': 'Toxicological profile for humans and animals',
'8.1': 'Other test(s) related to the exposure to humans ',
'8.1.1': 'Skin irritation / corrosion',
'8.1.2': 'Eye irritation',
'8.10.1': 'Pre-natal developmental toxicity study',
'8.10.2': 'Two-generation reproductive toxicity study',
'8.11': 'Carcinogenicity',
'8.12.1': 'Medical surveillance data on manufacturing plant personnel',
'8.12.6': 'Sensitisation data (humans)',
'8.13.2': 'Neurotoxicity',
'8.13.3': 'Endocrine disruption',
'8.13.4': 'Immunotoxicity',
'8.13.6': 'Specific investigations',
'8.14': 'Studies related to the exposure of humans to the active substance',
'8.15': 'Toxic effects on livestock and pets',
'8.16.1': 'Proposed acceptable residue levels i.e. maximum residue limits (MRL) and the justification of their acceptability',
'8.16.2': 'Behaviour of the residue of the active substance on the treated or contaminated food or feeding stuffs including the kinetics of disappearance',
'8.16.4': 'Estimation of potential or actual exposure of humans to the active substance and residues through diet and other means',
'8.16.5': 'If residues of the active substance occur in or on feeding stuffs for a significant period of time or also residues found in food of animal origin after treatment on or around food- producing animals (e.g. direct treatment on animals or indirect treatment of animal houses or surroundings) then Feeding and metabolism studies in livestock shall be required to permit evaluation of residues in food of animal origin',
'8.16.6': 'Effects of industrial processing and/or domestic preparation on the nature and magnitude of residues of the active substance',
'8.3': 'Skin sensitisation',
'8.3.1': 'Skin sensitisation',
'8.3.2': 'Respiratory sensitisation',
'8.5': 'Acute toxicity',
'8.5.1': 'Acute toxicity: oral',
'8.5.2': 'Acute toxicity: inhalation',
'8.5.3': 'Acute toxicity: dermal',
'8.5.4': 'Acute toxicity: product combinations',
'8.5.5': 'Genetic toxicity in vivo',
'8.6': 'Dermal absorption',
'8.7.1': 'other endpoints',
'8.7.2': 'Acute toxicity: inhalation',
'8.7.3': 'Acute toxicity: dermal',
'8.8': 'Food and feedingstuffs studies',
'8.8.1': 'Further toxicokinetic and metabolism studies in mammals',
'8.8.2': 'Dermal absorption',
'8.9': 'Effects of industrial processing and/or domestic preparation on the nature and magnitude of residues of the biocidal product',
'8.9.4': 'Further repeated dose studies',
'8.9.5.1': 'Repeated dose toxicity: oral',
'8.9.5.2': 'Repeated dose toxicity: inhalation',
'8.9.5.3': 'Repeated dose toxicity: dermal',
'9': 'ECOTOXICOLOGICAL STUDIES',
'9.1.1': 'Short-term toxicity testing on fish ',
'9.1.10': 'Effects on aquatic macrophytes',
'9.1.2': 'Short-term toxicity testing on aquatic invertebrates',
'9.1.3': 'Growth inhibition study on algae',
'9.1.5': 'Inhibition of microbial activity',
'9.1.6.1': 'Long term toxicity testing on fish ',
'9.1.6.2': 'Long term toxicity testing on invertebrates ',
'9.1.7': 'Bioaccumulation in an appropriate aquatic species',
'9.1.8': 'Effects on any other specific, non-target organisms (flora and fauna) believed to be at risk',
'9.1.9': 'Studies on sediment dwelling organisms',
'9.10.1': 'Endocrine disrupter testing in aquatic vertebrates – in vivo',
'9.10.2': 'Identification of endocrine activity',
'9.2': 'Further ecotoxicological studies',
'9.2.1': 'Effects on soil microorganisms',
'9.2.1.1': 'Short-term toxicity testing on fish ',
'9.2.1.10': 'Effects on aquatic macrophytes',
'9.2.1.2': 'Short-term toxicity to aquatic invertebrates',
'9.2.1.3': 'Growth inhibition study on algae',
'9.2.1.5': 'Inhibition of microbial activity',
'9.2.1.6': 'Further toxicity studies on aquatic organisms',
'9.2.1.6.1': 'Long term toxicity testing on fish ',
'9.2.1.6.2': 'Long term toxicity testing on invertebrates ',
'9.2.1.7': 'Bioaccumulation in an appropriate aquatic species',
'9.2.1.8': 'Effects on any other specific, non-target organisms (flora and fauna) believed to be at risk',
'9.2.1.9': 'Studies on sediment dwelling organisms',
'9.2.2': 'Terrestrial toxicity, initial tests',
'9.2.2.1': 'Effects on soil microorganisms',
'9.2.2.2': 'Effects on earthworms or other soil-dwelling non-target invertebrates',
'9.2.2.3': 'Acute toxicity to plants',
'9.2.3': 'Acute toxicity to plants',
'9.2.4': 'Effects on birds',
'9.2.5': 'Effects on arthropods',
'9.2.6': 'Bioconcentration terrestrial',
'9.2.8': 'Effects on other non-target, non-aquatic organisms',
'9.4': 'Effects on birds',
'9.5': 'Effects on arthropods',
'9.6': 'Bioconcentration terrestrial',
'9.8': 'Effects on other non-target, non-aquatic organisms',
'CORE numbering (1.10)': 'No Annex II requirement',
'CORE numbering (1.2)': 'No Annex II requirement',
'CORE numbering (1.3)': 'No Annex II requirement',
'CORE numbering (1.4)': 'No Annex II requirement',
'CORE numbering (1.5)': 'No Annex II requirement',
'CORE numbering (1.6)': 'No Annex II requirement',
'CORE numbering (1.8)': 'No Annex II requirement',
'CORE numbering (1.9)': 'No Annex II requirement',
'CORE numbering (11)': 'No Annex II requirement',
'CORE numbering (12)': 'No Annex II requirement',
'CORE numbering (13)': 'No Annex II requirement',
'CORE numbering (2.3)': 'No Annex II requirement',
'CORE numbering (2.4)': 'No Annex II requirement',
'CORE numbering (3.2)': 'No Annex II requirement',
'CORE numbering (3.4)': 'No Annex II requirement',
'CORE numbering (3.5.0)': 'No Annex II requirement',
'CORE numbering (3.5.1)': 'No Annex II requirement',
'CORE numbering (3.5.2)': 'No Annex II requirement',
'CORE numbering (3.5.3)': 'No Annex II requirement',
'CORE numbering (3.5.4)': 'No Annex II requirement',
'CORE numbering (3.5.5)': 'No Annex II requirement',
'CORE numbering (3.5.6)': 'No Annex II requirement',
'CORE numbering (3.6.1)': 'No Annex II requirement',
'CORE numbering (3.6.2)': 'No Annex II requirement',
'CORE numbering (3.6.3)': 'No Annex II requirement',
'CORE numbering (3.6.4)': 'No Annex II requirement',
'CORE numbering (3.6.5)': 'No Annex II requirement',
'CORE numbering (3.7)': 'No Annex II requirement',
'CORE numbering (4.16)': 'No Annex II requirement',
'CORE numbering (4.17)': 'No Annex II requirement',
'CORE numbering (4.2)': 'No Annex II requirement',
'CORE numbering (4.21)': 'No Annex II requirement',
'CORE numbering (4.28.1)': 'No Annex II requirement',
'CORE numbering (4.28.10)': 'No Annex II requirement',
'CORE numbering (4.28.11)': 'No Annex II requirement',
'CORE numbering (4.28.12)': 'No Annex II requirement',
'CORE numbering (4.28.13)': 'No Annex II requirement',
'CORE numbering (4.28.2)': 'No Annex II requirement',
'CORE numbering (4.28.3)': 'No Annex II requirement',
'CORE numbering (4.28.4)': 'No Annex II requirement',
'CORE numbering (4.28.5)': 'No Annex II requirement',
'CORE numbering (4.28.6)': 'No Annex II requirement',
'CORE numbering (4.28.7)': 'No Annex II requirement',
'CORE numbering (4.28.8)': 'No Annex II requirement',
'CORE numbering (4.28.9)': 'No Annex II requirement',
'CORE numbering (4.3)': 'No Annex II requirement',
'CORE numbering (4.5)': 'No Annex II requirement',
'CORE numbering (4.6)': 'No Annex II requirement',
'CORE numbering (4.7)': 'No Annex II requirement',
'CORE numbering (4.8)': 'No Annex II requirement',
'CORE numbering (4.9)': 'No Annex II requirement',
'CORE numbering (5.1)': 'No Annex II requirement',
'CORE numbering (5.1.1)': 'No Annex II requirement',
'CORE numbering (5.1.2)': 'No Annex II requirement',
'CORE numbering (5.1.3)': 'No Annex II requirement',
'CORE numbering (5.1.4)': 'No Annex II requirement',
'CORE numbering (5.2)': 'No Annex II requirement',
'CORE numbering (5.2.1)': 'No Annex II requirement',
'CORE numbering (5.2.2)': 'No Annex II requirement',
'CORE numbering (5.2.3)': 'No Annex II requirement',
'CORE numbering (5.2.4)': 'No Annex II requirement',
'CORE numbering (5.3)': 'No Annex II requirement',
'CORE numbering (5.3.1)': 'No Annex II requirement',
'CORE numbering (5.4)': 'No Annex II requirement',
'CORE numbering (5.4.1)': 'No Annex II requirement',
'CORE numbering (5.4.2)': 'No Annex II requirement',
'CORE numbering (5.5)': 'No Annex II requirement',
'CORE numbering (5.5.1)': 'No Annex II requirement',
'CORE numbering (5.5.2)': 'No Annex II requirement',
'CORE numbering (5.7)': 'No Annex II requirement',
'CORE numbering (6.1.1)': 'No Annex II requirement',
'CORE numbering (6.1.2)': 'No Annex II requirement',
'CORE numbering (6.1.4)': 'No Annex II requirement',
'CORE numbering (6.1.5)': 'No Annex II requirement',
'CORE numbering (6.1.6)': 'No Annex II requirement',
'CORE numbering (6.3.1)': 'No Annex II requirement',
'CORE numbering (6.3.2)': 'No Annex II requirement',
'CORE numbering (6.3.3)': 'No Annex II requirement',
'CORE numbering (6.3.5)': 'No Annex II requirement',
'CORE numbering (6.4)': 'No Annex II requirement',
'CORE numbering (6.5)': 'No Annex II requirement',
'CORE numbering (7)': 'No Annex II requirement',
'CORE numbering (7.1)': 'No Annex II requirement',
'CORE numbering (7.10)': 'No Annex II requirement',
'CORE numbering (7.11)': 'No Annex II requirement',
'CORE numbering (7.12)': 'No Annex II requirement',
'CORE numbering (7.2.1)': 'No Annex II requirement',
'CORE numbering (7.5)': 'No Annex II requirement',
'CORE numbering (7.6)': 'No Annex II requirement',
'CORE numbering (7.7)': 'No Annex II requirement',
'CORE numbering (7.8)': 'No Annex II requirement',
'CORE numbering (7.9.1)': 'No Annex II requirement',
'CORE numbering (7.9.2)': 'No Annex II requirement',
'CORE numbering (7.9.4)': 'No Annex II requirement',
'CORE numbering (9)': 'No Annex II requirement',
'CORE numbering (9.1)': 'No Annex II requirement',
'CORE numbering (9.2)': 'No Annex II requirement',
'CORE numbering (9.3)': 'No Annex II requirement',
'CORE numbering (9.4)': 'No Annex II requirement',
'CORE numbering (9.5)': 'No Annex II requirement',
'OECD numbering (16)': 'No Annex II requirement',
'OECD numbering (17)': 'No Annex II requirement',
'OECD numbering (2)': 'No Annex II requirement',
'OECD numbering (201)': 'No Annex II requirement',
'OECD numbering (21)': 'No Annex II requirement',
'OECD numbering (24)': 'No Annex II requirement',
'OECD numbering (25)': 'No Annex II requirement',
'OECD numbering (26)': 'No Annex II requirement',
'OECD numbering (27)': 'No Annex II requirement',
'OECD numbering (28)': 'No Annex II requirement',
'OECD numbering (29)': 'No Annex II requirement',
'OECD numbering (3)': 'No Annex II requirement',
'OECD numbering (30)': 'No Annex II requirement',
'OECD numbering (31)': 'No Annex II requirement',
'OECD numbering (34)': 'No Annex II requirement',
'OECD numbering (35)': 'No Annex II requirement',
'OECD numbering (37)': 'No Annex II requirement',
'OECD numbering (38)': 'No Annex II requirement',
'OECD numbering (39)': 'No Annex II requirement',
'OECD numbering (401)': 'No Annex II requirement',
'OECD numbering (43)': 'No Annex II requirement',
'OECD numbering (44)': 'No Annex II requirement',
'OECD numbering (48-2)': 'No Annex II requirement',
'OECD numbering (5)': 'No Annex II requirement',
'OECD numbering (53)': 'No Annex II requirement',
'OECD numbering (55)': 'No Annex II requirement',
'OECD numbering (56)': 'No Annex II requirement',
'OECD numbering (58)': 'No Annex II requirement',
'OECD numbering (6)': 'No Annex II requirement',
'OECD numbering (63)': 'No Annex II requirement',
'OECD numbering (66-3)': 'No Annex II requirement',
'OECD numbering (67)': 'No Annex II requirement',
'OECD numbering (68)': 'No Annex II requirement',
'OECD numbering (69-1)': 'No Annex II requirement',
'OECD numbering (69-2)': 'No Annex II requirement',
'OECD numbering (7)': 'No Annex II requirement',
'OECD numbering (70)': 'No Annex II requirement',
'OECD numbering (71)': 'No Annex II requirement',
'OECD numbering (72)': 'No Annex II requirement',
'OECD numbering (73)': 'No Annex II requirement',
'OECD numbering (74)': 'No Annex II requirement',
'OECD numbering (75)': 'No Annex II requirement',
'OECD numbering (75-3)': 'No Annex II requirement',
'OECD numbering (76)': 'No Annex II requirement',
'OECD numbering (77)': 'No Annex II requirement',
'OECD numbering (78)': 'No Annex II requirement',
'OECD numbering (79)': 'No Annex II requirement',
'OECD numbering (8)': 'No Annex II requirement',
'OECD numbering (80)': 'No Annex II requirement',
'OECD numbering (81)': 'No Annex II requirement',
'OECD numbering (82)': 'No Annex II requirement',
'OECD numbering (83)': 'No Annex II requirement',
'OECD numbering (84)': 'No Annex II requirement',
'OECD numbering (85-1)': 'No Annex II requirement',
'OECD numbering (85-10)': 'No Annex II requirement',
'OECD numbering (85-3)': 'No Annex II requirement',
'OECD numbering (85-4)': 'No Annex II requirement',
'OECD numbering (85-5)': 'No Annex II requirement',
'OECD numbering (85-8)': 'No Annex II requirement',
'OECD numbering (85-9)': 'No Annex II requirement',
'OECD numbering (9)': 'No Annex II requirement',
'OECD numbering (90)': 'No Annex II requirement',
'OECD numbering (Other)': 'No Annex II requirement',
'Regulatory specific numbering': 'No Annex II requirement'}
>
